name: Laravel Food Ordering

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      # - name: Run Tests
      #   run: php artisan test

      # ðŸ”” Build failed
      - name: Notify Slack (Build Failed)
        if: failure()
        run: |
          bash .github/scripts/slack-notify.sh \
            build failed \
            "Laravel Food Ordering" \
            "${{ github.ref_name }}" \
            "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # ðŸ”” Build success
      - name: Notify Slack (Build Success)
        if: success()
        run: |
          bash .github/scripts/slack-notify.sh \
            build success \
            "Laravel Food Ordering" \
            "${{ github.ref_name }}" \
            "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.APP_PATH }}
            bash deploy.sh

      # ðŸ”” Deploy failed
      - name: Notify Slack (Deploy Failed)
        if: failure()
        run: |
          bash .github/scripts/slack-notify.sh \
            deploy failed \
            "Laravel Instagram Ordering" \
            "${{ github.ref_name }}" \
            "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            "production"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # ðŸ”” Deploy success
      - name: Notify Slack (Deploy Success)
        if: success()
        run: |
          bash .github/scripts/slack-notify.sh \
            deploy success \
            "Laravel Instagram Ordering" \
            "${{ github.ref_name }}" \
            "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            "production"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
